name: cs5242
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pillow
  - tqdm
  - joblib
  - ipython
  - datasets
  - pip
  - pip:
      - thop
